### ISSUE TITLE
Challange admin page

### ISSUE THREAD

**Issue by ohoncharuk** [ohoncharuk/DelphiInternship#10]

**Comment by DimaLupyak** [comment]
**# Done**

![capture](https://cloud.githubusercontent.com/assets/7827224/13221922/57eeaa04-d986-11e5-91bd-38b92f0d0ff2.PNG)
![capture2](https://cloud.githubusercontent.com/assets/7827224/13221924/5b452bd8-d986-11e5-8f62-ada0fb7e13eb.PNG)
